### PR TITLE
Fix #261: RE 2, random BGM requires RE1 installation

### LINKED ISSUE #261: RE 2, random BGM requires RE1 installation
I set up BioRand the other day with my installation of RE2 SourceNext, and didn't have RE1 installed.

I noticed that I couldn't generate a seed with randomised music - I was getting the error message "RE1 installation must be enabled to use RE1 assets.". However I didn't actually have RE1 selected as a BGM source so I should be able to generate a seed with randomised music as long as the other game isn't selected.

Looked at making a fix before creating this issue - I noticed that, before generating a seed, there is a check to see if the other game's BGM is selected, and if it is and that game is not installed, then the seed will not be generated and that error message will be displayed.

However, this check doesn't actually check which game BGMs are actually selected, it just checks if that game's name (either RE1 or RE2) is present in a hash set composed of RE1, RE2 and the names of any BGM folders. RE1 and RE2 are always present in this hash set so it will always think that you selected RE1 or RE2.

Going to link a fix shortly that should fix this issue - essentially just need to check RandoConfig.EnabledBGMs to see if the BGM is actually selected.

### PR DESCRIPTION
**Pull request by HazNut**
Fixes #261

### CODE REVIEW

**Comment by IntelOrca** [comment]
> First attempt at an actual code contribution to open source, so let me know if I missed anything - not sure if I need to have this issue assigned to myself, and if I should add myself to CONTRIBUTORS.md if my changes make it through (not sure if someone else is supposed to do it)?

Sure, add yourself to CONTRIBUTORS.md

**Review by IntelOrca — APPROVED** [review]

**Comment by HazNut** [comment]
> > First attempt at an actual code contribution to open source, so let me know if I missed anything - not sure if I need to have this issue assigned to myself, and if I should add myself to CONTRIBUTORS.md if my changes make it through (not sure if someone else is supposed to do it)?
> 
> Sure, add yourself to CONTRIBUTORS.md

Thanks, will do that tonight - should that be in this PR or a separate one?

**Comment by IntelOrca** [comment]
> Thanks, will do that tonight - should that be in this PR or a separate one?

You can use the same PR.

**Comment by HazNut** [comment]
Have added myself to the list :)

**Pull request merged**
